[package]
name = "project-soap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vosk = "0.2.0"
serde_json = "1.0.117"
hound = "3.5.1"
clap = "4.5.7"

